name: 🐛 Bug Report
description: Report a bug or issue with faff
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us diagnose and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened and what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command: `...`
        2. With git diff: `...`
        3. Error occurs
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe the expected outcome
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually occurred
    validations:
      required: true

  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: Full error message or output (if any)
      render: shell
      placeholder: Paste the complete error message here
    validations:
      required: false

  - type: textarea
    id: git-diff
    attributes:
      label: Git Diff (if relevant)
      description: The git diff that was being processed when the error occurred
      render: diff
      placeholder: Paste the git diff output here if relevant to the issue
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Your operating system and version
      placeholder: e.g., Ubuntu 22.04, macOS 14.0, Windows 11 WSL2
    validations:
      required: true

  - type: input
    id: bash-version
    attributes:
      label: Shell Version
      description: Your shell and version
      placeholder: e.g., bash 5.1.16, zsh 5.8, fish 3.6.0
    validations:
      required: true

  - type: input
    id: ollama-version
    attributes:
      label: Ollama Version
      description: Your Ollama version
      placeholder: Run `ollama --version` to get this
    validations:
      required: true

  - type: input
    id: faff-version
    attributes:
      label: faff Version
      description: Your faff version or commit hash
      placeholder: e.g., latest main branch, commit abc123def
    validations:
      required: true

  - type: input
    id: model
    attributes:
      label: Ollama Model
      description: Which model you're using
      placeholder: e.g., qwen2.5-coder:7b
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Add any other relevant information, screenshots, or context
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided all the requested information above
          required: true
        - label: I can reproduce this issue consistently
          required: false
